spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: ${postgresql-password}
  jpa:
    open-in-view: false