spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    driver-class-name: org.postgresql.Driver
    password: ${PGPASSWORD}
  devtools:
    restart:
      enabled: true
  jpa:
    open-in-view: false
